export const CarouselDots = () => {
  return (
    <div className="absolute box-border caret-transparent break-words text-center bottom-2 inset-x-0 md:bottom-5">
      <div className="box-border caret-transparent break-words w-full left-0 bottom-2">
        <span className="bg-transparent box-content caret-black inline h-auto w-auto mx-0 rounded-none md:aspect-auto md:bg-blue-600 md:box-border md:caret-transparent md:inline-block md:h-2 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
        <span className="bg-transparent box-content caret-black inline h-auto opacity-100 w-auto mx-0 rounded-none md:aspect-auto md:bg-black md:box-border md:caret-transparent md:inline-block md:h-2 md:opacity-20 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-2 md:[mask-position:0%] md:bg-left-top md:mx-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></span>
      </div>
    </div>
  );
};
