export const DisclaimerSection = () => {
  return (
    <section className="box-border caret-transparent tracking-[-0.8px] md:tracking-[-1.2px]">
      <div className="relative box-border caret-transparent tracking-[-0.8px] text-left overflow-hidden md:tracking-[-1.2px]">
        <div className="relative box-border caret-transparent tracking-[-0.8px] max-w-full mx-auto px-5 md:tracking-[-1.2px] md:max-w-[750px] md:px-[30px]">
          <div className="text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] pb-10 md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:pb-16">
            <div className="relative text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] pt-6 md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:pt-9 before:accent-auto before:caret-transparent before:text-black before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-px before:left-[-200%] before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:right-[-200%] before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:top-0 before:font-nanumsquareneo before:md:text-lg before:md:tracking-[-0.3px] before:md:leading-[29px]">
              <h5 className="text-neutral-700 text-sm font-extrabold box-border caret-transparent tracking-[-0.2px] leading-[19px] mt-1 md:text-[21px] md:tracking-[-0.3px] md:leading-[29px] md:mt-1.5">
                필수 유의사항
              </h5>
              <ul className="text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] list-none mt-3 pl-0 md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-[18px]">
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버 현대카드 연회비 : 국내전용/국내외겸용(Visa)
                  10,000원(발급 종료 상품)
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버 현대카드 Edition2 연회비 : 국내전용/국내외겸용(Visa
                  Platinum/Amex Platinum) 20,000원
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  <em className="text-neutral-700 text-xs font-bold box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]">
                    카드 이용 대금 연체 시 약정 금리 + 연체 가산 금리 3%의 연체
                    금리가 적용됩니다.(회원별, 이용 상품별 차등 적용/법정 최고
                    금리 20% 이내)
                    <br className="text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]" />
                    단, 연체 발생 시점에 약정 금리가 없는 경우 아래와 같이 적용
                    <br className="text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]" />
                    - 일시불 : 거래 발생 시점 기준 최소 기간(2개월)의 유이자
                    할부 약정 금리 + 연체 가산 금리 3%
                    <br className="text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]" />
                    - 무이자 할부 : 거래 발생 시점 기준 동일한 할부 계약 기간의
                    유이자 할부 약정 금리 + 연체 가산 금리 3%
                  </em>
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  <em className="text-neutral-700 text-xs font-bold box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]">
                    상환 능력에 비해 신용카드 이용금액이 과도할 경우, 귀하의
                    개인신용평점이 하락할 수 있습니다.
                  </em>
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  <em className="text-neutral-700 text-xs font-bold box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]">
                    개인신용평점 하락 시 금융거래와 관련된 불이익이 발생할 수
                    있습니다.
                  </em>
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  <em className="text-neutral-700 text-xs font-bold box-border caret-transparent tracking-[-0.2px] leading-[19px] md:text-lg md:tracking-[-0.3px] md:leading-[29px]">
                    일정 기간 원리금을 연체할 경우, 모든 원리금을 변제할 의무가
                    발생할 수 있습니다.
                  </em>
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  신용카드 발급이 부적정한 경우(연체금 보유, 개인신용평점 낮음
                  등) 카드 발급이 제한될 수 있습니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  카드 이용대금과 이에 수반되는 모든 수수료를 지정된 대금
                  결제일에 상환합니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  금융소비자는 금융소비자보호법 제19조 제1항에 따라 해당 상품
                  또는 서비스에 대하여 설명을 받을 권리가 있습니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  자세한 내용 및 이용 조건은 카드 신청 전 현대카드 홈페이지 및
                  상품설명서, 약관 참고
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버는 현대카드의 신용카드 회원 모집 업무를 대리·중개합니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버는 다수의 금융회사를 대리하거나 중개합니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버는 현대카드의 금융상품에 대한 계약체결권한이 없습니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버는 금융관계법률에 따라 등록되어 있는
                  금융상품판매대리·중개업자입니다.
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  네이버(주) 사업자등록번호 220-81-62517, 멤버십 고객센터
                  대표전화 1599-1399
                </li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]"></li>
                <li className="relative text-stone-500 text-xs box-border caret-transparent tracking-[-0.2px] leading-[19px] align-top mt-1 pl-[9px] md:text-lg md:tracking-[-0.3px] md:leading-[29px] md:mt-2 md:pl-3 before:accent-auto before:bg-neutral-400 before:caret-transparent before:text-stone-500 before:block before:text-xs before:not-italic before:normal-nums before:font-normal before:h-0.5 before:tracking-[-0.2px] before:leading-[19px] before:list-outside before:list-none before:pointer-events-auto before:absolute before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:left-0 before:top-[9px] before:font-nanumsquareneo before:md:text-lg before:md:h-[3px] before:md:tracking-[-0.3px] before:md:leading-[29px] before:md:w-[3px] before:md:top-[13px]">
                  여신금융협회 심의필 제 2026-C1h-01885호 (2026.02.11 ~
                  2027.02.09)
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
