export const PhoneSection = () => {
  return (
    <div className="items-center box-border caret-transparent flex justify-center min-h-[auto] min-w-[auto] break-words w-full">
      <div className="box-border caret-transparent flex max-w-none min-h-[360px] min-w-[auto] break-words w-full rounded-[17px] md:max-w-[1400px] md:min-h-[700px] md:rounded-[33px]">
        <div className="relative box-border caret-transparent flex basis-[0%] grow min-h-[auto] min-w-[auto] break-words z-[1] overflow-hidden">
          <div className="relative items-center bg-[radial-gradient(circle,rgb(252,253,255),rgb(196,206,255))] box-border caret-transparent flex basis-[0%] grow justify-center min-h-[auto] min-w-[auto] break-words z-50 rounded-[17px] md:bg-[radial-gradient(circle,rgb(252,253,255),rgb(196,206,255),rgb(196,206,255))] md:rounded-[33px]">
            <div className="box-border caret-transparent h-[150px] min-h-[auto] min-w-[auto] break-words w-[150px] md:h-[300px] md:w-[300px]">
              <img
                alt=""
                src="https://c.animaapp.com/mn4j4i5rMNHjkT/assets/star.0d~z-k65.khs~.png"
                className="text-transparent aspect-[auto_300_/_300] box-border h-full max-w-full break-words align-baseline w-full"
              />
            </div>
          </div>
          <div className="static bg-transparent shadow-none box-content caret-black opacity-100 transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/10 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:blur-[9.33333px] md:opacity-[0.733333] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:-translate-x-20 md:translate-y-[-367px] md:w-[350px] md:z-[14] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[0.21] md:left-0 md:top-0"></div>
          <div className="static bg-transparent shadow-none box-content caret-black opacity-100 transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/20 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:blur-[9.16667px] md:opacity-[0.716667] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[529px] md:translate-y-[-368.5px] md:w-[350px] md:z-[15] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[0.225] md:left-0 md:top-0"></div>
          <div className="static bg-transparent shadow-none box-content caret-black opacity-100 transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/40 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:blur-[5.66667px] md:opacity-[0.366667] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[775px] md:translate-y-[-280px] md:w-[350px] md:z-[36] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[0.54] md:left-0 md:top-0"></div>
          <div className="static bg-transparent shadow-none box-content caret-black transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/50 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[898px] md:translate-y-[-332.5px] md:w-[350px] md:z-[51] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[0.765] md:left-0 md:top-0"></div>
          <div className="static bg-transparent shadow-none box-content caret-black opacity-100 transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/10 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:blur-[9.83333px] md:opacity-[0.783333] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[944px] md:translate-y-[-272.5px] md:w-[350px] md:z-[11] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[0.165] md:left-0 md:top-0"></div>
          <div className="static bg-transparent shadow-none box-content caret-black opacity-100 transform-none w-auto z-auto rounded-none border-y-0 border-black left-auto top-auto md:absolute md:aspect-auto md:backdrop-blur-[10px] md:bg-white/40 md:border-l-slate-200 md:border-r-slate-200 md:shadow-[rgba(0,0,0,0.1)_0px_20px_10px_0px] md:box-border md:caret-transparent md:blur-[2.25px] md:opacity-55 md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[804px] md:translate-y-[-481px] md:w-[350px] md:z-[90] md:[mask-position:0%] md:bg-left-top md:p-[30px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:border-y-white/70 md:border-y-2 md:border-solid md:scale-[1.35] md:left-0 md:top-0"></div>
        </div>
      </div>
    </div>
  );
};
